name: Build and deploy Python app to Azure Web App - EdunetSalaryPredictionApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository so the workflow can access your code
      - uses: actions/checkout@v2

      # Step 2: Set up the specific version of Python you are using
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install all the necessary dependencies from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy the application to your Azure Web App
      # This single step handles zipping the code, sending it to Azure,
      # and running the build process on the server.
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EdunetSalaryPredictionApp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b95afa5fa501448fb78a4ac394d8aaab }}
          package: . # Deploy the entire repository
